# Generated by Django 4.1.7 on 2023-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhouse', '0008_alter_cut_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
